spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/technodom
    username: postgres
    password: 2005Wppt++
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
